### PR TITLE
Fix spelling and include RangeAttribute in validation

### PR DESCRIPTION
**Pull request by Toxantron**
I received feedback about a spelling error in EntryValidation and the idea, to make the value more flexible and also include range validation values.

### CODE REVIEW

**Review by dbeuchler — APPROVED** [review]
The renaming must also be fixed within the maintenance web.

**Comment by Toxantron** [comment]
> The renaming must also be fixed within the maintenance web.

I checked and the MaintenanceWeb does currently not include validation AFAIK.

**Comment by dbeuchler** [comment]
> > The renaming must also be fixed within the maintenance web.
> 
> I checked and the MaintenanceWeb does currently not include validation AFAIK.

I think you missed the deserialization: https://github.com/PHOENIXCONTACT/MORYX-MaintenanceWeb/blob/dev/src/Moryx.Runtime.Maintenance.Web.UI/src/modules/models/EntryValidation.ts

**Comment by Toxantron** [comment]
Yes I did :-)

**Pull request merged**
