### PR TITLE
Added cors support behavior

### PR DESCRIPTION
**Pull request by mmarkwort**
Solves #49

### CODE REVIEW

**Comment by Toxantron** [comment]
Just one question: Is this by any chance code from Stackoverflow? If not, I agree adding CORS.

**Comment by mmarkwort** [comment]
> 
> 
> Just one question: Is this by any chance code from Stackoverflow? If not, I agree adding CORS.

Unfortunately this code comes in Parts from Stackoverflow

**Comment by Toxantron** [comment]
> Unfortunately this code comes in Parts from Stackoverflow

Because Stackoverflow failed to go through with licensing their snippets under MIT license, all of that is still **CC-BY-SA** and incompatible with our Apache License.

**Comment by Toxantron** [comment]
I reduced it to pure CORS implementation, that should not violate any Copyright, as it is an almost empty implementation that only sets CORS headers and should fall below *threshold of originality*.

**Review by Toxantron — APPROVED** [review]

**Pull request merged**
